### ISSUE TITLE
Build/host on Railway?

### ISSUE THREAD

**Issue by tomkail** [AgoraIO/agora-rtt-server#1]
Hi! We're using Agora's Unity API, and are interested in this package - but we know _very_ little about hosting server applications. Your starter docs guided us through setting up a token server using Railway, and we were wondering if we could do the same thing here - would deploying this repo from Railway work?
If not - what's the easiest and fastest way to get set up with this project?

**Comment by saudsami** [comment]
Hi Tom
One-click deployment of the RTT server on Railway is a great idea, and we're working on making it possible.
We're committed to providing you with the easiest and fastest way to get set up with this project. We appreciate your patience, and we'll make sure to update you as soon as we have the one-click deployment process ready.

**Comment by tomkail** [comment]
Thanks! Is this planned to happen anytime soon? We'd quite like to implement this in the next week or so.

**Comment by saudsami** [comment]
Hi Tom,
I have updated the code, configuration, and README file for deployment to Railway.
https://github.com/AgoraIO/agora-rtt-server#one-click-deployment-on-railway

**Comment by tomkail** [comment]
Brilliant! Thanks so much!
