### ISSUE TITLE
Failed to run mvn clean install command

### ISSUE THREAD

**Issue by Hi-Fella** [AgoraIO/agora-rtt-server#4]
I would like to try the **agora-rtt-server** project in my local device such as my windows. I've already installed **maven 3.9.6** and JDK version is 17.0.9. But there is an error show up, i need help from agora team.

![image](https://github.com/AgoraIO/agora-rtt-server/assets/155937235/1f48fa83-561e-4e81-bdd2-a28626dee812)
![image](https://github.com/AgoraIO/agora-rtt-server/assets/155937235/ab6563d4-4360-4e74-864b-31ad5376f375)
![image](https://github.com/AgoraIO/agora-rtt-server/assets/155937235/19801258-5bc5-402f-8013-7c80084caee2)

**Comment by saudsami** [comment]
Hi
To contact the Agora support team, please create a support ticket from Agora Console.
https://www.agora.io/en/talk-to-us/
